CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(512) NOT NULL,
    password VARCHAR(512) NOT NULL,
    role VARCHAR(64) NOT NULL,
    balance DECIMAL,
    blocked BOOLEAN,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS organizations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(2000),
    logo VARCHAR(512),
    blocked BOOLEAN,
    owner_id BIGINT NOT NULL ,
    CONSTRAINT pk_organization PRIMARY KEY (id),
    CONSTRAINT fk_organization_on_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS products
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(64) NOT NULL,
    price DECIMAL NOT NULL,
    organization_id BIGINT NOT NULL,
    warehouse_amount BIGINT,
    blocked BOOLEAN,
    CONSTRAINT pk_product PRIMARY KEY (id),
    CONSTRAINT fk_product_on_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS purchases
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    buyer_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    price DECIMAL NOT NULL,
    date_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_purchase PRIMARY KEY (id),
    CONSTRAINT fk_purchase_on_buyer FOREIGN KEY (buyer_id) REFERENCES users (id),
    CONSTRAINT fk_purchase_on_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_purchase_on_seller FOREIGN KEY (seller_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS discounts
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(256) NOT NULL,
    value DECIMAL NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_discount PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product_discounts
(
    discount_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT pk_product_discounts PRIMARY KEY (discount_id, product_id),
    CONSTRAINT fk_discount_products_on_discounts FOREIGN KEY (discount_id) REFERENCES discounts (id),
    CONSTRAINT fk_discount_products_on_products FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE IF NOT EXISTS notifications
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    admin_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE,
    title VARCHAR(512) NOT NULL,
    text VARCHAR(7000) NOT NULL,
    CONSTRAINT pk_notification PRIMARY KEY (id),
    CONSTRAINT fk_notification_on_admin FOREIGN KEY (admin_id) REFERENCES users (id),
    CONSTRAINT fk_notification_on_user FOREIGN KEY (recipient_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS reviews
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE,
    text VARCHAR(7000) NOT NULL,
    CONSTRAINT pk_review PRIMARY KEY (id),
    CONSTRAINT fk_review_on_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_review_on_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE IF NOT EXISTS marks
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE,
    mark INTEGER NOT NULL,
    CONSTRAINT pk_mark PRIMARY KEY (id),
    CONSTRAINT fk_mark_on_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_mark_on_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE IF NOT EXISTS keywords
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    word VARCHAR(128),
    CONSTRAINT pk_word PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product_keywords
(
    product_id BIGINT NOT NULL,
    keyword_id BIGINT NOT NULL,
    CONSTRAINT pk_product_keywords PRIMARY KEY (product_id, keyword_id),
    CONSTRAINT fk_product_keywords_on_keywords FOREIGN KEY (keyword_id) REFERENCES keywords (id),
    CONSTRAINT fk_product_keywords_on_products FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE IF NOT EXISTS product_specifications
(
    name VARCHAR(256) NOT NULL,
    value VARCHAR(256) NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT pk_name PRIMARY KEY (name),
    CONSTRAINT fk_specification_on_product FOREIGN KEY (product_id) REFERENCES products (id)
);